version: '3'

services:
  db:
    image: postgres
    container_name: options-finder-postgres
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql
  prod:
    image: options-finder
    container_name: options-finder-prod
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
  dev:
    image: options-finder
    container_name: options-finder-dev
    volumes:
      - ./app:/app # Mount a volume in the dev mode so we don't have to keep rebuilding the image
    env_file: database.conf
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:5432

volumes:
  db_volume: